project:
  type: website

website:
  title: "ISSS608 Coursework"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise 0"
        href: Handson-Exercise/Handson_00/Handson_Ex00.html
      - text: "Hands-on Exercise 1"
        href: Handson-Exercise/Handson_01/Handson_Ex01.html
    - text: "In-Class Exercise"
      menu:
      - text: "In-class Exercise 1"
        href: In-class_Ex1.html
    - text: "Take home Exercise"
      menu:
      - text: "Take home Exercise 1"
        href: Take home_Ex1.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - pulse
      - brand
    css: styles.css
    toc: true

editor: visual

