---
title: "17  Visualising and Analysing Time-oriented Data"
author: "TzuTing Hunag"
date: "February 25, 2025"
date-modified: "last-modified"
execute:
  warning: false
---

## **17.1 Learning Outcome**

-   plotting a calender heatmap by using ggplot2 functions,

-   plotting a cycle plot by using ggplot2 function,

-   plotting a slopegraph

-   plotting a horizon chart

## **17.2 Getting Started**

```{R}
pacman::p_load(scales, viridis, lubridate, ggthemes, gridExtra, readxl, knitr, data.table, CGPfunctions, ggHoriPlot, tidyverse)

```

## **17.3 Plotting Calendar Heatmap**

Let's plot a calender heatmap

### **17.3.2 Importing the data**

```{R}
attacks <- read_csv ("data_1/eventlog.csv")
```

### **17.4.3 Examining the data structure**

```{R}
kable(head(attacks))

```

There are three columns namely:

-   ***timestamp** :* date-time values in POSIXct format.

-   ***source_country :*** the source of the attack. It is in *ISO 3166-1 alpha-2* country code.

-   ***tz :*** time zone of the source IP address.

### **17.4.4 Data Preparation**

Step 1: Deriving *weekday* and *hour of day* fields

```{R}
make_hr_wkday <- function(ts, sc, tz) {
  real_times <- ymd_hms(ts, 
                        tz = tz[1], 
                        quiet = TRUE)
  dt <- data.table(source_country = sc,
                   wkday = weekdays(real_times),
                   hour = hour(real_times))
  return(dt)
}
```

-   [`ymd_hms()`](https://lubridate.tidyverse.org/reference/ymd_hms.html) and [`hour()`](https://lubridate.tidyverse.org/reference/hour.html) are from [**lubridate**](https://lubridate.tidyverse.org/) package, and

-   [`weekdays()`](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/weekdays) is a **base** R function.

Step 2: Deriving the attacks tibble data frame

```{R}
wkday_levels <- c('Saturday', 'Friday', 
                  'Thursday', 'Wednesday', 
                  'Tuesday', 'Monday', 
                  'Sunday')

attacks <- attacks %>%
  group_by(tz) %>%
  do(make_hr_wkday(.$timestamp, 
                   .$source_country, 
                   .$tz)) %>% 
  ungroup() %>% 
  mutate(wkday = factor(
    wkday, levels = wkday_levels),
    hour  = factor(
      hour, levels = 0:23))
```

mutate() of **dplyr** package is used to convert *wkday* and *hour* fields into **factor** so they’ll be ordered when plotting

```{R}
kable(head(attacks))

```

### **17.4.5 Building the Calendar Heatmaps**

```{R}
grouped <- attacks %>% 
  count(wkday, hour) %>% 
  ungroup() %>%
  na.omit()

ggplot(grouped, 
       aes(hour, 
           wkday, 
           fill = n)) + 
geom_tile(color = "white", 
          size = 0.1) + 
theme_tufte(base_family = "Helvetica") + 
coord_equal() +
scale_fill_gradient(name = "# of attacks",
                    low = "#F1E1FF", 
                    high = "dark blue") +
labs(x = NULL, 
     y = NULL, 
     title = "Attacks by weekday and time of day") +
theme(axis.ticks = element_blank(),
      plot.title = element_text(hjust = 0.5),
      legend.title = element_text(size = 8),
      legend.text = element_text(size = 6) )
```

**\
Things to learn from the code chunk**

-   a tibble data table called *grouped* is derived by aggregating the attack by *wkday* and *hour* fields.

-   a new field called *n* is derived by using `group_by()` and `count()` functions.

-   `na.omit()` is used to exclude missing value.

-   `geom_tile()` is used to plot tiles (grids) at each x and y position. `color` and `size` arguments are used to specify the border color and line size of the tiles.

-   [`theme_tufte()`](https://jrnold.github.io/ggthemes/reference/theme_tufte.html) of [**ggthemes**](https://jrnold.github.io/ggthemes/reference/index.html) package is used to remove unnecessary chart junk. To learn which visual components of default ggplot2 have been excluded, you are encouraged to comment out this line to examine the default plot.

-   `coord_equal()` is used to ensure the plot will have an aspect ratio of 1:1.

-   `scale_fill_gradient()` function is used to creates a two colour gradient (low-high).

we can simply group the count by hour and wkday and plot it

### **17.4.6 Building and Plotting Multiple Calendar Heatmaps**

Building multiple heatmaps for the top four countries with the highest number of attacks.

Step 1: Deriving attack by country object

In order to identify the top 4 countries with the highest number of attacks, you are required to do the followings:

-   count the number of attacks by country,

-   calculate the percent of attackes by country, and

-   save the results in a tibble data frame.

```{R}
attacks_by_country <- count(
  attacks, source_country) %>%
  mutate(percent = percent(n/sum(n))) %>%
  arrange(desc(n))
```

Step 2: Preparing the tidy data frame

1.  extract the attack records of the top 4 countries from *attacks* data frame

2.  save the data in a new tibble data frame (i.e. *top4_attacks*).

```{R}
top4 <- attacks_by_country$source_country[1:4]
top4_attacks <- attacks %>%
  filter(source_country %in% top4) %>%
  count(source_country, wkday, hour) %>%
  ungroup() %>%
  mutate(source_country = factor(
    source_country, levels = top4)) %>%
  na.omit()
```

### **17.4.8 Plotting Multiple Calendar Heatmaps**

Step 3: Plotting the Multiple Calender Heatmap by using ggplot2 package.

```{R}
ggplot(top4_attacks, 
       aes(hour, 
           wkday, 
           fill = n)) + 
  geom_tile(color = "white", 
          size = 0.1) + 
  theme_tufte(base_family = "Helvetica") + 
  coord_equal() +
  scale_fill_gradient(name = "# of attacks",
                    low = "#F1E1FF", 
                    high = "dark blue") +
  facet_wrap(~source_country, ncol = 2) +
  labs(x = NULL, y = NULL, 
     title = "Attacks on top 4 countries by weekday and time of day") +
  theme(axis.ticks = element_blank(),
        axis.text.x = element_text(size = 7),
        plot.title = element_text(hjust = 0.5),
        legend.title = element_text(size = 8),
        legend.text = element_text(size = 6) )
```

## **17.5 Plotting Cycle Plot**

plot a cycle plot showing the time-series patterns and trend of visitor arrivals from Vietnam programmatically

### **17.5.1 Step 1: Data Import**

```{R}
air <- read_excel("data_1/arrivals_by_air.xlsx")
```

### **17.5.2 Step 2: Deriving month and year fields**

Next, two new fields called *month* and *year* are derived from *Month-Year* field.

```{R}
air$month <- factor(month(air$`Month-Year`), 
                    levels=1:12, 
                    labels=month.abb, 
                    ordered=TRUE) 
air$year <- year(ymd(air$`Month-Year`))
```

### **17.5.3 Step 3: Extracting the target country**

Next, the code chunk below is use to extract data for the target country (i.e. Vietnam)

```{R}
Vietnam <- air %>% 
  select(`Vietnam`, 
         month, 
         year) %>%
  filter(year >= 2010)
```

### **17.5.4 Step 4: Computing year average arrivals by month**

The code chunk below uses `group_by()` and `summarise()` of **dplyr** to compute year average arrivals by month.

```{R}
hline.data <- Vietnam %>% 
  group_by(month) %>%
  summarise(avgvalue = mean(`Vietnam`))
```

### **17.5.5 Srep 5: Plotting the cycle plot**

```{R}
ggplot() + 
  geom_line(data=Vietnam,
            aes(x=year, 
                y=`Vietnam`, 
                group=month), 
            colour="black") +
  geom_hline(aes(yintercept=avgvalue), 
             data=hline.data, 
             linetype=6, 
             colour="red", 
             size=0.5) + 
  facet_grid(~month) +
  labs(axis.text.x = element_blank(),
       title = "Visitor arrivals from Vietnam by air, Jan 2010-Dec 2019") +
  xlab("") +
  ylab("No. of Visitors") +
  theme_tufte(base_family = "Helvetica")
```

## **17.6 Plotting Slopegraph**

make sure that **CGPfunctions** has been installed and loaded onto R environment.

### **17.6.1 Step 1: Data Import**

```{R}
rice <- read_csv("data_1/rice.csv")
```

### **17.6.2 Step 2: Plotting the slopegraph**

```{R}
rice %>% 
  mutate(Year = factor(Year)) %>%
  filter(Year %in% c(1961, 1980)) %>%
  newggslopegraph(Year, Yield, Country,
                Title = "Rice Yield of Top 11 Asian Counties",
                SubTitle = "1961-1980",
                Caption = "Prepared by: Dr. Kam Tin Seong")
```

**\
Thing to learn from the code chunk above**

For effective data visualisation design, `factor()` is used convert the value type of *Year* field from numeric to factor.
