---
title: "12  Funnel Plots for Fair Comparisons"
author: "TzuTing Huang, (Hannah)"
date: "February 1, 2025"
date-modified: "last-modified"
execute:
  warning: false
---

## **12.1 Overview**

-   plotting funnel plots by using **funnelPlotR** package,

-   plotting static funnel plot by using ggplot2 package, and

-   plotting interactive funnel plot by using both **plotly R** and **ggplot2** packages.

## **12.2 Installing and Launching R Packages**

-   **readr** for importing csv into R.

-   **FunnelPlotR** for creating funnel plot.

-   **ggplot2** for creating funnel plot manually.

-   **knitr** for building static html table.

-   **plotly** for creating interactive funnel plot.

```{R}
pacman::p_load(tidyverse, FunnelPlotR, plotly, knitr)
```

The code chunk below imports the data into R and save it into a tibble data frame object called *covid19*.

```{R}
covid19 <- read_csv("data/COVID-19_DKI_Jakarta.csv") %>%
  mutate_if(is.character, as.factor)
```

## **12.4 FunnelPlotR methods**

### **12.4.1 FunnelPlotR methods: The basic plot**

The code chunk below plots a funnel plot.

```{R}
funnel_plot(
  .data = covid19,
  numerator = Positive,
  denominator = Death,
  group = `Sub-district`
)
```

### **12.4.2 FunnelPlotR methods: Makeover 1**

The code chunk below plots a funnel plot.

```{R}
funnel_plot(
  .data = covid19,
  numerator = Death,
  denominator = Positive,
  group = `Sub-district`,
  data_type = "PR",     #<<
  x_range = c(0, 6500),  #<<
  y_range = c(0, 0.05)   #<<
)
```

### **12.4.3 FunnelPlotR methods: Makeover 2**

The code chunk below plots a funnel plot.

```{R}
funnel_plot(
  .data = covid19,
  numerator = Death,
  denominator = Positive,
  group = `Sub-district`,
  data_type = "PR",   
  x_range = c(0, 6500),  
  yrange = c(0, 0.05),
  label = NA,
  title = "Cumulative COVID-19 Fatality Rate by Cumulative Total Number of COVID-19 Positive Cases", #<<           
  x_label = "Cumulative COVID-19 Positive Cases", #<<
  y_label = "Cumulative Fatality Rate"  #<<
)
```
